#ifndef QUADRATICEQUATION_EQUATIONRESULT_H
#define QUADRATICEQUATION_EQUATIONRESULT_H

#endif //QUADRATICEQUATION_EQUATIONRESULT_H

enum EquationResult {
    INF_ROOTS = 1,
    NO_ROOTS = 2,
    ONE_ROOT = 3,
    TWO_ROOTS = 4,
};
